### ISSUE TITLE
Arguments for ords_manual_install.sql don't work

### ISSUE THREAD

**Issue by GasparYYC** [OraOpenSource/OXAR#112]
Hi,
 I'm trying to install but many errors with ORDS 3.0.3 
On script: ords.sh  the call to run ords_manual_install.sql seem to have the wrong arguments, possibly previous versions of ORDS required at least different order.
New Order is:
Arguments:
1  : Log folder (must include the forward slash at the end)
2  : Default tablespace for ORDS_METADATA
3  : Temporary tablespace for ORDS_METADATA
4  : Default tablespace for ORDS_PUBLIC_USER
5  : Temporary tablespace for ORDS_PUBLIC_USER

In the header there is some information related:
Rem     epaglina    12/10/2015 Removing prompting default and temporary tablespaces for ORDS Public User.
Rem                            Must be passed as a parameter. Bug 22336058.

This is the line I used:
```
sqlplus sys/oracle as sysdba @ords_manual_install.sql ${ORDS_SOURCE_DIR}/scripts/ -DEFAULT -DEFAULT -DEFAULT -DEFAULT << EOF1
${OOS_ORDS_PUBLIC_USER_PASSWORD}
EOF1
```

Note: The 'DEFAULT' are case sensitive
Note2: A different directory should be used since it's been removed at this point in the code. This is the error. Not critical but not good:

LOGFILENAME
-------------------------------------------------------------------------
/root/oxar/tmp/ords/scripts/ordsinstall_2015-12-26_22_43_57_843062.log

SP2-0606: Cannot create SPOOL file "/root/oxar/tmp/ords/scripts/ordsinstall_2015-12-26_22_43_57_843062.log"

Thanks

**Comment by tschf** [comment]
Arguments difference?

3.0.1:

```
Rem      1  : Default tablespace name for ORDS schema
Rem      2  : Temporary tablespace name for ORDS schema
Rem      3  : Path of log file (include the forward slash at the end)
```

3.04

```
Rem      1  : Log folder (must include the forward slash at the end)
Rem      2  : Default tablespace for ORDS_METADATA
Rem      3  : Temporary tablespace for ORDS_METADATA
Rem      4  : Default tablespace for ORDS_PUBLIC_USER
Rem      5  : Temporary tablespace for ORDS_PUBLIC_USER
```

**Comment by tschf** [comment]
All documented here: http://docs.oracle.com/cd/E56351_01/doc.30/e56293/install.htm#CHDFJHEA
