### ISSUE TITLE
Npm not installing properly

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/OXAR#128]
Linux CentOS 7 x64

In `packages.sh` I don't think we need `curl -sL https://rpm.nodesource.com/setup | bash -` as the repo should be taken care of by `yum`. See https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-a-centos-7-server for more info.

Also need to explicitly install `npm`

**Comment by tschf** [comment]
Closing since this has already been updated to use the package manager.
