### ISSUE TITLE
sed: can't read ords_manual_create_rest_users.sql: No such file or directory

### ISSUE THREAD

**Issue by mallkuma** [OraOpenSource/OXAR#139]
CentOS 7.2 x64, error.log has the following messages:

`sed: can't read ords_manual_create_rest_users.sql: No such file or directory
Mar 12, 2016 8:29:32 AM oracle.dbtools.cmdline.ModifyConfigDir execute
INFO: Set config.dir to /etc in: /tmp/oxar/tmp/ords/ords.war
Mar 12, 2016 8:38:21 AM oracle.dbtools.rt.config.setup.SchemaSetup getSchemaVersion
WARNING: Failed to connect to user ORDS_PUBLIC_USER jdbc:oracle:thin:@localhost:1521:xe 
IO Error: Connection reset
Mar 12, 2016 8:38:21 AM oracle.dbtools.common.config.file.ConfigurationFilesBase update
INFO: Updated configurations: defaults, apex, apex_pu, apex_al, apex_rt
Mar 12, 2016 8:38:21 AM oracle.dbtools.rt.config.setup.SchemaSetup install
WARNING: Cannot connect to the database to check if ORDS is installed or upgrade is required`

**Comment by tschf** [comment]
What ORDS version are you using? Latest?

**Comment by mallkuma** [comment]
Yes, 3.0.4.60.12.48

**Comment by mallkuma** [comment]
Please note that I cannot find the ORDS_PUBLIC_USER nor ORDS_METADATA.

I wanted to access REST services via SQL Developer so I manually added "admin" and "dev" ORDS users using ords.war. Once the users were added, I was able to connect to "ORDS Administration" in SQL Developer without any issues. However, when I am connected to the HR schema in SQL Developer, I do not get "REST Services" -> "Enable REST Services" option on the schema context menu.

**Comment by tschf** [comment]
Duplicate for #112
