### ISSUE TITLE
Tomcat installation - RPMDB altered outside of yum and prompted to replace server.xml

### ISSUE THREAD

**Issue by mallkuma** [OraOpenSource/OXAR#140]
Not sure if this is an issue but thought of posting it here. Please label the issue as needed.

CentOS 7.2 x64 via putty: Sometime during the installation process, right before the installation of Tomcat begins, I am getting the prompt...
* Installing Tomcat *
Warning: RPMDB altered outside of yum.
cp: overwrite '/usr/share/tomcat/conf/server.xml?'

I typed "Y" and the installation process continued.

**Comment by tschf** [comment]
Looks like that RPMDB message is about using `rpm` for package management without using `yum`. According to this - https://www.howtoforge.com/yum-warning-rpmdb-altered-outside-of-yum - `yum clean all` should resolve that warning.

**Comment by tschf** [comment]
The issue here though is getting prompted to replace server.xml - Need to add the `-f` option.

**Comment by tschf** [comment]
Replacing server.xml resolved in #150
