### ISSUE TITLE
Enable report printing

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/OXAR#142]
Set to ORDS in instance settings.

See: http://www.oracle.com/webfolder/technetwork/tutorials/obe/db/apex/r50/PDF%20Printing/Creating%20PDF%20Reports%20with%20Oracle%20Application%20Express%205.0%20and%20Oracle%20REST%20Data%20Services.html#overview

![screenshot from 2016-03-30 12 03 32](https://cloud.githubusercontent.com/assets/1747643/14128757/8f7323e6-f66f-11e5-8b1e-ca8382036712.png)

May also help:

http://www.oracle.com/technetwork/developer-tools/apex/learnmore/custom-pdf-reports-1953918.pdf

**Comment by martindsouza** [comment]
I think we can do this with `apex_instance_admin.set_parameter` and parameter [`PRINT_BIB_LICENSED`](https://docs.oracle.com/cd/E59726_01/doc.50/e39149/apex_instance.htm#AEAPI248)

We already have a file for managing the APEX instance: https://github.com/OraOpenSource/OXAR/blob/master/apex/apex_config.sql Perhaps we can add it in there.

**Comment by tschf** [comment]
Yeah cool, easy fix :) Just tested (just to double check), and it works well using the documented values.

```plsql
 exec apex_instance_admin.set_parameter('PRINT_BIB_LICENSED', 'APEX_LISTENER');
```
