### ISSUE TITLE
lsb_release fails in Oracle Linux

### ISSUE THREAD

**Issue by janihur** [OraOpenSource/OXAR#146]
I'm trying Vagrant installation in Windows 10. I use the default `Vagrantfile` and hence boxcutter/ol72 base box (Oracle Linux).

The installation fails because Oracle Linux doesn't support `lsb_release` command.

```
PS C:\src\oxar> vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'boxcutter/ol72' is up to date...
[...]
==> default: utils/os/permit_root_ssh_login.sh
==> default:
==> default: sent 199763 bytes  received 1363 bytes  134084.00 bytes/sec
==> default: total size is 195184  speedup is 0.97
==> default: /tmp/vagrant-shell: line 15: lsb_release: command not found
==> default:
==> default: * Loading configurations *
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
PS C:\src\oxar>
```

The problem in `Vagrantfile` shell provisioner:

```bash
    if [[ `lsb_release -i` =~ (Ubuntu) ]]; then
      sed -i s/^.*$/UTC/ /etc/timezone;
    fi
```

One way to identify Oracle Linux version:
 
```
login as: root
root@127.0.0.1's password:
Last login: Sat Apr  9 16:57:29 2016
----------------------------------------------------------------
  Oracle Enterprise Linux 7.2                 built 2016-01-05
----------------------------------------------------------------
[root@localhost ~]# lsb_release -i
-bash: lsb_release: command not found
[root@localhost ~]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[root@localhost ~]# rpm -qf /etc/redhat-release
oraclelinux-release-7.2-1.0.5.el7.x86_64
[root@localhost ~]#
```

**Comment by fuzziebrain** [comment]
Thanks for your feedback. I am aware that some of the Linux flavours do not have `lsb_release` out of the box. It was not a showstopper during my tests though. Did the process abort during your attempt to provision the VM using Vagrant? Which version of Vagrant are you on?

**Comment by janihur** [comment]
Yes, the provisioning process aborted (as you should see from the attached log), but I was able to continue manually (i.e. logged into linux and run build.sh manually as root) and got XE up and running without major fuss.

```
PS C:\src\oxar> vagrant --version
Vagrant 1.8.1
PS C:\src\oxar>
```

**Comment by fuzziebrain** [comment]
Yes, I can see that, but I have encountered during my tests that the build proceeds despite the error. Wanted to be sure, as I haven't seen this causing a full break during provisioning process. I will definitely look into a more stable method to detect the underlying OS. Thank you again for the feedback.

**Comment by tschf** [comment]
#158 removed the usage of lsb_release. I guess this can be closed now? @fuzziebrain

**Comment by fuzziebrain** [comment]
Indeed. Thanks for reminding me about this one.
