### ISSUE TITLE
Use a real provisoner instead of shell scripts

### ISSUE THREAD

**Issue by janihur** [OraOpenSource/OXAR#148]
I tried (and succeeded !) to create an OXAR sandbox for my personal use (I'm mainly interested in Oracle DB only). I used to have a Turnkey [Oracle XE appliance](https://github.com/janihur/turnkey-oracle-xe-11g/tree/initial-dev) but I think the Vagrant based solution is just better and I'm more than happy to abandon that for OXAR.

A recent versions of Vagrant support many providers of which I'm most familiar with Ansible. Current OXAR provisioning logic seems to be "too complex" for shell scripts so I started to write an Ansible provisioner. I'm not an Ansible expert but I'm well-versed enough to get the ball rolling.

You can follow-up the development at:

https://github.com/janihur/OXAR/tree/vagrant-ansible

The used features require Vagrant 1.8.0+.

The current version just kicks XE up and the implementation is not yet very modular nor fully idempotent. However I wanted to write a very straightforward first implementation to see that OXAR really can provisioned with Ansible.

Ansible is not a walk in the park either but it is a tool especially designed for automated system configuration (unlike the shell scripts) and the very same playbook can be used also for production deployments. Please see the `ansible/oxar.yml` file and tell what you think about pivoting from shell scripts to Ansible.

I've start with [boxcutter/centos72](https://atlas.hashicorp.com/boxcutter/boxes/centos72). If the main purpose is just to get a Oracle sandbox it doesn't essentially matter what Linux distribution is used.

**Comment by janihur** [comment]
I have now implemented the first "fully functional" Oracle XE installation with Vagrant [Ansible Local](https://www.vagrantup.com/docs/provisioning/ansible_local.html) provisioner that works with [boxcutter/centos72](https://atlas.hashicorp.com/boxcutter/boxes/centos72). Everything is in a big fat playbook without [roles](http://docs.ansible.com/ansible/playbooks_roles.html#roles).

Just put the Oracle XE zip file in the right place and chant `vagrant up`.

```
jani@mcbook:~/p/oxar$ ll ansible/files/
total 617008
drwxr-xr-x  7 jani  staff   238B Apr 17 10:39 ./
drwxr-xr-x  6 jani  staff   204B Apr 17 20:28 ../
-rw-r--r--  1 jani  staff   115B Apr 14 20:46 20oos_oraclexe.sh
-rw-r--r--@ 1 jani  staff   301M Apr 10 15:46 oracle-xe-11.2.0-1.0.x86_64.rpm.zip
-rw-r--r--  1 jani  staff   165B Apr 17 08:23 oracle_config.sql
-rw-r--r--  1 jani  staff   1.4K Apr 17 08:23 oracle_create_user.sql
-rw-r--r--  1 jani  staff   179B Apr 17 10:39 unlock_sample_data.sql
jani@mcbook:~/p/oxar$
```

Comments welcome.

**Comment by martindsouza** [comment]
@janihur I'm not too familiar with Ansible. OXAR does support Vagrant ( @fuzziebrain set it up). 

Regarding this ticket, what do you want to add to OXAR for it? We won't have a "base Oracle XE" only as that's not the purpose of OXAR. As you pointed out it's a lot easier to provision your own machine if that's all you need.

re: OXAR being complicated to setup. I agree. We really wanted a "no-config" install but we can't as Oracle licensing does not allow us to provide the install files for their products.

**Comment by janihur** [comment]
Well I guess the main point is that there is superior tools compared to shell scripts. My initial effort here was just focused on "base Oracle XE" because I know nothing about the rest of the OXAR stack. The example should give you a concrete example how Ansible could be applied to OXAR.

If you'll continue on the shell script path then this issue can be closed and ignored. I'll be happy to use OXAR as long as it delivers even when powered with shell scripts.

**Comment by martindsouza** [comment]
@janihur yes we plan to continue with shell scripts for the foreseeable future. Of course that could change. Overall yes Oracle XE will still work. The only ports we expose by default or 80 (for APEX) and 22 for ssh. Other than that if you don't want to use any of the other tools that are installed then it won't negatively affect the system.
