### ISSUE TITLE
Validate ORDS 3.0.6

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/OXAR#159]
Released today.

Release notes - https://docs.oracle.com/cd/E56351_01/doc.30/e56294/toc.htm#AELRN101

> The following changes and enhancements have been made since 3.0.5:
BUG:23638987 - Fix regression causing APEX Based RESTful Services to fail if and only if the ORDS_PUBLIC_USER (???_pu.xml) connection pool is removed.
BUG:23625255 - Fix regression causing performance degradation due to unnecessary validation of database pools
BUG:23504343 - Fix the localization of the install help command
BUG:23347319 - Fix regression causing IllegalStateExecption when context path accessed without trailing slash
BUG:23291056 - Enable support for TLS 1.2 with JDBC connections, by upgrading to use the most recently available Oracle JDBC drivers for JDK 7
BUG:23314519 - Fix regression causing corruption of values in OWA CGI environment

> The following change and enhancements have been made to the Simple Oracle Document Access (SODA) functionality:
BUG:23563847 - New default indexing mode: requires scalars, missing values allowed.

> BUG:23500034 - Includes the following fixes:
New indexing modes: "scalarRequired", "lax".
Result limit applies to QBE queries as well as basics gets.
Order-bys and indexes no longer implicitly append [0] steps.
Rest error messages no longer hard-code "type" attribute to 400 code definition (correct definition now used).
BUG:23316761 - RestResponse needs to guard against null exception check.

>BUG:23500034 - Includes the following fixes:
Fixes URI patterns issue for cloud.
Adds correct exception handling for future releases, in the case of deleting collection with uncommitted writes.
Fixes commit/rollback issues in SODA REST handler.
If-match headers (optimistic locking).

**Comment by fuzziebrain** [comment]
I'll be testing this against a Vagrant build. Let me know if I should add to the list:
- [ ] Oracle Linux 7.2
- [ ] Centos 7.2
- [ ] Ubuntu 16.04
- [ ] Ubuntu 14.04.4 LTS
- [ ] Debian 8.2

**Comment by tschf** [comment]
Just tested, all working well on CentOS 7.2 for me

**Comment by martindsouza** [comment]
Closing this ticket as we now have ORDS 3.0.7
