### ISSUE TITLE
Issue with Digital Ocean and CentOs 7.2

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/OXAR#161]
As posted from the OOS blog: http://www.oraopensource.com/blog/2015/2/25/video-how-to-build-oracle-xe-apex-machine

> I've created a new Droplet on DigitalOcean and tried to use OXAR to configure everything but with no success. Everything installs correctly but when I connect to the server it shows a blank page. http://server/i/apex_version.txt shows correct APEX version.
I've tried with CentOS 6.8 and 7.2 because 7.0 is not available.
I'm a newbie configuring Oracle and APEX so I might be missing something basic. Any suggestions?

**Comment by pedropalmares** [comment]
I found out that this problem only happens when creating a Droplet with 512Mb RAM. With the 1Gb Droplet it works correctly. Is this a limitation?

**Comment by martindsouza** [comment]
@pedropalmares Yes, Oracle needs 1gb of RAM to work. I had tested with a 1GB machine but it didn't work. Still looking into it.

**Comment by pedropalmares** [comment]
@martindsouza It worked on mine (CentOS, converted to Oracle Linux 7.2, already with Apex 5.0.4). I haven't tested it thoroughly but at least it logins.
