### ISSUE TITLE
Delay tomcat startup

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/OXAR#165]
Can we somehow delay Tomcats startup until Oracle is up and running? Had an issue today where I had to manually restart tomcat as the database wasn't up and running when ORDS started up and thus /ords returned a 404 error (until restarting Tomcat)

**Comment by fuzziebrain** [comment]
Maybe a `post_install.sh`? I have had a different issue with ORDS 3.0.6. Had to touch `/etc/ords/tomcat` before restarting Tomcat.

**Comment by tschf** [comment]
Was thinking one solution could be to convert oracle to a systemd service, then I believe you can have a dependency chain. Haven't investigated how easy this is for the oracle-xe sysV init script.

https://fedoramagazine.org/systemd-converting-sysvinit-scripts/

**Comment by martindsouza** [comment]
@tschf I've had the same issue that after the initial OXAR reboot am getting the ORDS `404` error. Fix is to restart again. Would be good if we didn't have to do this and also a lot less confusing for others.

**Comment by tschf** [comment]
Yes, it's on my radar. I made a start trying to convert the SysInit script a while ago, but didn't get anywhere. Haven't had time to carry on.

**Comment by tschf** [comment]
Actually, I think converting it is an unnecessary step. 
We can try this. Edit `/usr/lib/systemd/system/tomcat.service`. and modify the line to be: `After=syslog.target network.target oracle-xe.service`.

I'll set this up soon - not sure of a good way to reliably reproduce the problem though.

**Comment by martindsouza** [comment]
@tschf only way I've encountered it is after an OXAR installation (right after the countdown reboot).

**Comment by tschf** [comment]
As per PR, I've added `oracle-xe` to the `After` setting in a new tomcat service file (tomcat@oxar.service) and for Debian, added to the `Should-Start` setting. Tomcat should now be started with `tomcat@oxar` rather than `tomcat` (the tomcat service is disabled in favour of tomcat@oxar).
