### ISSUE TITLE
In a debug mode, allow for pause/manual request between each step

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/OXAR#166]
Similar to #164 this will allow us to help isolate what is working when debugging a script.

From http://stackoverflow.com/questions/92802/what-is-the-linux-equivalent-to-dos-pause on how to "pause": `read -n1 -r -p "Press any key to continue..." key`

**Comment by martindsouza** [comment]
May be better to use `read -rsp $'Press enter to continue...\n'` instead

**Comment by martindsouza** [comment]
Have only done for Oracle and APEX. 

@tschf do you think we should add in the debug mode option for all the other main entities? We can add on an as-needed basis.

**Comment by tschf** [comment]
I think the main entities should be fine - XE, APEX, ORDS. I haven't tested yet - does the implementation terminate the install properly if I hit ctrl+c or ctrl+d? 

Just to document all (current) entities:

* updates/dependencies
* ratom
* XE*
* APEX*
* Node driver
* Tomcat
* Firewall config
* ORDS*
* SQLcl

**Comment by martindsouza** [comment]
@tschf not sure. It just pauses at the end of critical steps and requires the user to hit `enter` to continue. I've got XE, APEX, an ORDS as the critical break points now. If we need more we can simply add them.
