### ISSUE TITLE
Install PM2 for node.js development

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/OXAR#176]
Adding PM2 since it's an amazing tool to manage node.js processes. Will also replace node4ords process management as it will allow developers to watch the folder so that they can edit the app and have auto restart.

https://github.com/Unitech/pm2

- [x] List it as part of the tools we provide.
- [x] Launch node4ords from pm2 rather than `systemctl`
- [x] Remove `systemctl` commands and documentation
- [x] Ensure PM2 runs at startup AND with last config: https://github.com/Unitech/pm2

**Comment by fuzziebrain** [comment]
How about running node4ords through pm2 then?

**Comment by martindsouza** [comment]
@fuzziebrain great idea. We'll just need to ensure that we name the app when starting so we can start/stop via a name rather than id. Docs https://github.com/Unitech/pm2.

We can look at deprecating the `systemctl start/stop node4ords` command

**Comment by fuzziebrain** [comment]
Specifically this: `pm2 start app.js --name="api" # Start application and name it "api"`?
