### ISSUE TITLE
Debian (and Debian based Distro) Question to certbot

### ISSUE THREAD

**Issue by teotiger** [OraOpenSource/OXAR#187]
Hey,
thanks for this great project! However, I have found a issue regarding Debian and Debian based Distros like Ubuntu (and my Laptop-Favourite-Distro Elementary OS).

For example you are trying to install 'certbot' in file 'scripts/packages.sh' (line 42). But the package certbot doesn't exist in Ubuntu 16.04/Elementary OS 0.4. According to https://certbot.eff.org/ the package you need is called 'letsencrypt'. In Debian 8 it exists if you enable the Jessie backports repo (https://certbot.eff.org/#debianjessie-other) - a thing you have to know and to configure before you run the OXAR build script...

Regards,
markus

**Comment by martindsouza** [comment]
Dup of #191 . Will deal with it there.
