### ISSUE TITLE
What about OXAR versions?

### ISSUE THREAD

**Issue by teotiger** [OraOpenSource/OXAR#188]
Hey,
one general question: Have you think about publishing stable and tested "versions" of the OXAR project? What i mean is, months ago I installed successfully OXAR on Debian 8.5. Now I have problems (e.g. now i use ords.3.0.6.176.08.46.zip, time ago i used ords.3.0.0.121.10.23.zip) due to new features and improvements - but I can't download EASILY a old version which definitily worked out of the box on Debian 8.5.

Regards,
markus

**Comment by martindsouza** [comment]
@teotiger Funny you should bring this up. @fuzziebrain has been pushing this for a while. We're actually focused on doing this at the moment by cutting our official first release. We still have a few tickets to do and you can monitor here: https://github.com/OraOpenSource/OXAR/milestone/4

Once 1.0.0 is cut, the goal is to make this like every other project where we have releases that people can reference for their needs.

Thanks for the feedback.
