### ISSUE TITLE
File URL appears to be invalid

### ISSUE THREAD

**Issue by schunt1** [OraOpenSource/OXAR#190]
Hi Martin.  I am using a Debian VM and trying to run the build.sh.  Unfortunately all I get is the following error during the install:

The Oracle file URL specified, file:///tmp/oracle-xe-11.2.0-1.0.x86_64.rpm.zip, appears invalid.

See the attache screenshots.  I think I have followed the config correctly?
![debian2](https://cloud.githubusercontent.com/assets/2545233/19000070/8884d58e-8738-11e6-8e5c-8f0360680e0c.PNG)
![debian1](https://cloud.githubusercontent.com/assets/2545233/19000077/8f9c36f0-8738-11e6-8259-2d4e096d0e0d.PNG)
![debian3](https://cloud.githubusercontent.com/assets/2545233/19000144/e4477a70-8738-11e6-876a-e2f54abf35aa.PNG)

**Comment by tschf** [comment]
Does your system/VM have `curl` installed? The immediate previous errors
suggests not. You can install with `sudo apt-get install curl` in the
meantime.

**Comment by schunt1** [comment]
Great thanks, that worked.
