### ISSUE TITLE
Port 80 not working by default

### ISSUE THREAD

**Issue by GasparYYC** [OraOpenSource/OXAR#192]
_Note this was originally a suggestion which turned out to be a bug _

**Original Title: **: Use of Standard Ports
Not an issue but an enhancement request...

I would like to have OXAR use the standard ports (80, 443) because I'm running into more and more issues with companies not wanting to have/manage exclusions on their firewall(s).

My thoughts are that as an alternative a Forward-Proxy (or Reverse) kind of setup with Squid, Pound, Nginx, etc. will handle that gracefully without affecting OXAR existing setup and probably more secure by allowing OXAR be hidden (and more secure).

**Comment by tschf** [comment]
Doesn't it use the standard ports? Node4Ords (reverse proxy) uses port 80 as default, and almost all ports are configurable, right?

**Comment by GasparYYC** [comment]
Agreed. From that perspective it does use :80 but the APEX applications end up going via :8080 or :8443 for TLS (at least I couldn't get it to work on 443).
If there is a way to change the ports maybe it should be described in the documentation?

**Comment by tschf** [comment]
The [README](https://github.com/OraOpenSource/OXAR/blob/master/README.md#configure) says:

> Regardless of whether you're doing a native or Vagrant based build, you will need to modify the config.properties file prior to running the installation script. At a minimum, you will need to replace the CHANGME tokens to point to the appropriate files. Read below for help on modifying this file. If doing a Vagrant install, you can modify config.properties using your local text editor.

https://github.com/OraOpenSource/OXAR/blob/master/config.properties#L50

```
#TOMCAT Config
OOS_TOMCAT_PORT=8080
```

With that said, not sure why you would be accessing via :8080, node4ords reverse proxies there so from the outside world, you should juts need access to port 80. I believe Martin has also set it up to work with letsencrypt too, so 443 in that case.

**Comment by GasparYYC** [comment]
I guess when I installed OXAR I focused on the CHANGEME Tokens and nothing else.. I didn't know there was a reverse proxy setup... all I know is that it worked when I tried: http://<server_name>:8080/ords and directed me to the Login screen... I know I tried Port 80 did not work (possibly an early OXAR build?).
I didn't think of the consequences at that time..   My mistake.

On this topic you and I discussed briefly the same during early January.
Anyway, I will certainly investigate further.
Thanks for the guidance.

**Comment by martindsouza** [comment]
@GasparYYC I think this is a bug with port `80` not working on your system for some reason. What OS did you use? I'll label this as a bug for now. 

I've renamed the title to reflect this issue.

**Comment by GasparYYC** [comment]
@martindsouza Servers are CentOS version is 7.2
I know is an early build of OXAR (fall 2015) and possibly a missed port configuration on my part.
Very soon I'll create new OXAR on new server and will confirm to you if the ports are still non-standard.

**Comment by martindsouza** [comment]
@GasparYYC Since it's an old build and a lot has changed since then, closing this issue.
