### ISSUE TITLE
vagrant up build fails

### ISSUE THREAD

**Issue by eberhje** [OraOpenSource/OXAR#195]
On MacBook Pro I got everything ready and used the "vagrant up" scenario to build the machine.  Got errors during the packages script and failed installing Oracle XE.  In my local environment I modified the packages.sh and took out the certbot call.   Started over and then had success.

<img width="1010" alt="screenshot 2016-10-13 11 37 36" src="https://cloud.githubusercontent.com/assets/5177432/19400073/b34d995c-9211-11e6-897a-6e4d8b473701.png">

**Comment by fuzziebrain** [comment]
Hi Jeff. Did you use the default box which gives you an Oracle Linux VM? If so, can you please try commenting out line 19 and uncommenting line 20 in the file `Vagrantfile`?

**Comment by eberhje** [comment]
Yes, I was using the default box.  I changed it to centos as suggested and it completed.

**Comment by martindsouza** [comment]
@fuzziebrain is this fixed now?

**Comment by fuzziebrain** [comment]
Should be resolved now.
