### ISSUE TITLE
ORDS 3.0.8 Not supported in OXAR

### ISSUE THREAD

**Issue by GasparYYC** [OraOpenSource/OXAR#199]
I am testing latest version of OXAR and downloaded the latest version of ORDS (3.0.8) and received the message:
This version of ORDS is not yet supprted in OXAR
Please report this at http://github.com/OraOpenSource/oxar/issues

To "make it work" I changed the condition in scripts/config_validation.sh to:
``    elif [[ ! "${ORDS_MAJOR}.${ORDS_MINOR}.${ORDS_REVISION}" == "3.0.4" ]] \
        && [[ ! "${ORDS_MAJOR}.${ORDS_MINOR}.${ORDS_REVISION}" == "3.0.5" ]] \
        && [[ ! "${ORDS_MAJOR}.${ORDS_MINOR}.${ORDS_REVISION}" == "3.0.6" ]] \
        && [[ ! "${ORDS_MAJOR}.${ORDS_MINOR}.${ORDS_REVISION}" == "3.0.7" ]] \
        && [[ ! "${ORDS_MAJOR}.${ORDS_MINOR}.${ORDS_REVISION}" == "3.0.8" ]]; then``

I don't see any "interesting" new features since 3.0.6 which was the last supported version:

Changes in 3.0.8
Issues Fixed in 3.0.8
The following changes and enhancements have been made since 3.0.7:
BUG:23640212 - Fix regression preventing the externally authenticated user identity being propagated to the database via the REMOTE_USER CGI header variable
New Features since 3.0.7
None.

Changes in 3.0.7
Issues Fixed in 3.0.7
The following changes and enhancements have been made since 3.0.6:
BUG:24507612 - Fix regression preventing updating of an Application Express based OAuth Client Registration
BUG:24440967 - Address Connection resource leak that may occur under load.
BUG:24344949 - Show 503 Service unavailable status when database reports ORA-00018 Max Sessions Exceeded
BUG:24344949 - Retry request after jittered delay when database reports ORA-00018 Max Sessions Exceeded
BUG:23732108, BUG: 23732138 - Reduce overhead in dispatching all requests, improving performance.
The following changes and enhancements have been made to the Simple Oracle Document Access (SODA) functionality:
BUG:24450332 - Proper handling of 500 and 503 errors from ORDS. Now SODA JSON responses are returned, instead of ORDS responses.
BUG:24308373 - Support versioning in SODA URIs (version "v1" is supported, and is the only supported version at this time).
New Features since 3.0.6
ENH:24347162 - When PL/SQL Gateway uses APEX_PUBLIC_USER automatically add WWV_FLOW_EPG_INCLUDE_MODULES.AUTHORIZE to the security.requestValidationFunction setting

**Comment by GasparYYC** [comment]
I will report if ORDS 3.0.8 with OXAR downloaded on 2016-10-24 seems to be working..

**Comment by tschf** [comment]
There's also a version check in the ORDS script, as 3.0.4 had a different silent instal methodl. Tested with 3.0.8 and all working
