### ISSUE TITLE
ORDS 3.0.9: This version of ORDS is not yet supprted in OXAR

### ISSUE THREAD

**Issue by dgielis** [OraOpenSource/OXAR#213]
Do we want to support 3.0.9 too? (released 19-DEC)

**Comment by fuzziebrain** [comment]
I believe either @martindsouza or @tschf has already added support for ORDS 3.0.9. I just ran a build with that version of ORDS and it ran just fine.
![image](https://cloud.githubusercontent.com/assets/1829281/21448126/c46e4106-c893-11e6-9434-97f20f5c74a1.png)

**Comment by tschf** [comment]
As per previous comment, 3.0.9 is supported already. I just ran to double check. Closing.
