### ISSUE TITLE
Failing to install Oracle XE. Cannot find /etc/init.d/oracle-xe 

### ISSUE THREAD

**Issue by ST3WRAT** [OraOpenSource/OXAR#218]
MacBook Pro running OS X El Capitan 10.11.6.
VirtualBox version 5.1.2 r112440 (Qt5.6.2)
Downloaded files
	CentOS-7-x86_64-Minimal-1611.iso
	oracle-xe-11am.2.0-1.0.x86_64.rpm.zip
	ords.3.0.9.348.07.16.zip
	apex_5.1_en.zip
	sqlcl-4.2.0.16.355.0402-no-ire.zip

CentOS installed into VirtualBox 
root and an Administrator account set up.

Followed Martins video to put the above files onto the 'server'.
updated the config.properties file to reference the files as file:///top/???

ran build.sh

There were several warnings which seemed not to matter. I couldn't find the log file for this.  

When the script reached Installing Oracle XE, it displayed a counter up to 100% and then the script aborted with an error saying that it couldn't find folder /etc/init.d/oracle-xe

**Comment by ST3WRAT** [comment]
Typo on the oracle XE file name above - ignore the 11am - read it as 11

**Comment by martindsouza** [comment]
@ST3WRAT can you look into `/tmp/oxar/logs` (or similar to see if you can find any install logs. Something went wrong with the install and Oracle wasn't installed as `/etc/init.d/oracle-xe` is what launches Oracle XE.

**Comment by ST3WRAT** [comment]
Martin
Thanks for the speedy response.

The logs in /tmp/oraclexe-apex/logs showed that there was insufficient diskspace for the instal of Oracle XE - Message says that

Requesting to download file file:///tmp/oracle-xe-11.2.0-1.0.x86_64.rpm.zip
Download of file:///tmp/oracle-xe-11.2.0-1.0.x86_64.rpm.zip completed successfully
Archive:  oracle-xe-11.2.0-1.0.x86_64.rpm.zip
   creating: Disk1/
   creating: Disk1/upgrade/
  inflating: Disk1/upgrade/gen_inst.sql
   creating: Disk1/response/
  inflating: Disk1/response/xe.rsp
  inflating: Disk1/oracle-xe-11.2.0-1.0.x86_64.rpm
Preparing...                          ########################################
You have insufficient diskspace to install Oracle Database 11g Express Edition.
 The installation requires at least 1.5 GB free diskspace.

 .

According to my Centos VM environment I have a SATA Vdi environment with a Virtual Size of 8Gb and an actual size of 2.94 GB.

I thought the the inflation would extend the ‘disk’ unto the Virtual size.

Can you make any suggestions?

Thanks for your help (and Happy New Year)

Stewart

**Comment by martindsouza** [comment]
@ST3WRAT I usually configure mine to have 20gb of expandable storage. Try to rebuild with that setting. 

Here's what I used for a recent APEX 5.1 install on Virtual Box

![snip20170102_25](https://cloud.githubusercontent.com/assets/2925726/21599928/8cc8c982-d131-11e6-97a0-0b2294283524.png)

**Comment by ST3WRAT** [comment]
Martin,

That looks to have been the resolution. The install is happily chugging away.

Thanks again for the help.

Stewart
