### ISSUE TITLE
DNS related error with vagrant build

### ISSUE THREAD

**Issue by iMingLei** [OraOpenSource/OXAR#226]
I ran vagrant build from windows host. Annoying Error below prompted.

> ==> default: * Installing rsync with yum *
> ==> default: Loaded plugins: fastestmirror
> ==> default: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
> ==> default: 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"

**Comment by iMingLei** [comment]
According to [here ](https://www.centos.org/forums/viewtopic.php?t=55818), this might related to DNS. I will update DNS and re-build tomorrow.

**Comment by iMingLei** [comment]
Adding DNS server before install rsync will fix this curl related error. Tested with vagrant build. Native build doesn't prompt this error without any change.

```
  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   sudo apt-get update
  #   sudo apt-get install -y apache2
  # SHELL
 config.vm.provision "shell", inline: <<-SHELL
   export OOS_DEPLOY_TYPE="VAGRANT"

  + echo "nameserver 8.8.8.8" >> /etc/resolv.conf 

   if [ -n "$(command -v yum)" ]; then
     echo; echo \* Installing rsync with yum \*
   ...
```

**Comment by fuzziebrain** [comment]
Thanks for your feedback. Is this issue preventing you from completing the build with Vagrant? DNS resolution should be resolved through the host. Please see line 65 in the Vagrantfile. Can you please let me know what version of Vagrant and VirtualBox were you running?

**Comment by iMingLei** [comment]
This issue isn't preventing build. It's more like a warning from yum to check fastestmirror. I noticed line 65 and I did try to add this dns to host but not working.

I am working on windows host with babun, vagrant and virtualbox installed from chocolatey. 

```
$ echo `cmd /c ver`                                         
Microsoft Windows [Version 10.0.14393]

$ babun --version                                           
babun version 1.2.0

$ cygcheck --version                                        
cygcheck (cygwin) 1.7.35

$ zsh --version                                             
zsh 5.0.6 (i686-pc-cygwin)

$ vagrant --version        
Vagrant 1.9.1

$ VBoxManage --version                                      
5.1.14r112924
```

**Comment by fuzziebrain** [comment]
I would recommend just running vagrant from the Windows command line. If the packages are still installing then it looks like the VM isn't having issues resolving addresses.

**Comment by iMingLei** [comment]
I just did a quick build test via Windows command line. Unfortunately, the same error prompted.

> ==> oxarDev1:
==> oxarDev1: * Installing rsync with yum *
==> oxarDev1: Loaded plugins: fastestmirror
==> oxarDev1: Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=stock error was
==> oxarDev1: 14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Temporary failure in name resolution"
==> oxarDev1:
==> oxarDev1:
==> oxarDev1:  One of the configured repositories failed (Unknown),
==> oxarDev1:  and yum doesn't have enough cached data to continue. At this point the only
==> oxarDev1:  safe thing yum can do is fail. There are a few ways to work "fix" this:
==> oxarDev1:
==> oxarDev1:      1. Contact the upstream for the repository and get them to fix the problem.
==> oxarDev1:
==> oxarDev1:      2. Reconfigure the baseurl/etc. for the repository, to point to a working
==> oxarDev1:         upstream. This is most often useful if you are using a newer
==> oxarDev1:         distribution release than is supported by the repository (and the
==> oxarDev1:         packages for the previous distribution release still work).
==> oxarDev1:
==> oxarDev1:      3. Disable the repository, so yum won't use it by default. Yum will then
==> oxarDev1:         just ignore the repository until you permanently enable it again or use
==> oxarDev1:         --enablerepo for temporary usage:
==> oxarDev1:
==> oxarDev1:             yum-config-manager --disable <repoid>
==> oxarDev1:
==> oxarDev1:      4. Configure the failing repository to be skipped, if it is unavailable.
==> oxarDev1:         Note that yum will try to contact the repo. when it runs most commands,
==> oxarDev1:         so will have to try and fail each time (and thus. yum will be be much
==> oxarDev1:         slower). If it is a very temporary problem though, this is often a nice
==> oxarDev1:         compromise:
==> oxarDev1:
==> oxarDev1:             yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true
==> oxarDev1:
==> oxarDev1: Cannot find a valid baseurl for repo: base/7/x86_64
==> oxarDev1:
==> oxarDev1: * Source os-release for OS information *
==> oxarDev1: sending incremental file list

**Comment by fuzziebrain** [comment]
Ran the build a few times this past hour on two different machines. Same outcome. 
![image](https://cloud.githubusercontent.com/assets/1829281/23495609/8ed002de-fece-11e6-8cd2-2c65f7b8910a.png)
