### ISSUE TITLE
Documentation to upgrade APEX

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/OXAR#233]
Most people who use this project aren't DBAs and don't know how to upgrade APEX.

Should there be an upgrade documentation?

**Comment by tschf** [comment]
Related to #99. 

Pretty much I think for free users, you need to backup all apps and workspaces, also config in internal workspace, then uninstall and reinstall. I worked briefly on this in a project I called daxul, but probably needs some more love - bit experimental with the config export / import.

**Comment by vincentmorneau** [comment]
What do you mean "free user"?

So there's no way around a complete reinstall for a patch?

**Comment by fuzziebrain** [comment]
I believe @tschf is referring to Oracle XE users. Patch releases are only downloadable through MOS. You need to have a support contract with Oracle.

**Comment by tschf** [comment]
> What do you mean "free user"?

> I believe @tschf is referring to Oracle XE users. Patch releases are only downloadable through MOS.

Yes, exactly this. There is no way for me, as in independent developer, to get access to the patch sets. So, the only way for me to upgrade APEX would be drop it and re-install the latest version.

Of course, there are also people who use XE that do have a support contract (through work) and do have access to MOS. Maybe you're thinking of some docs for that scenario (where they can get the patch sets).

**Comment by tschf** [comment]
Closing this in favour of 99.
