### ISSUE TITLE
Identity column in AOP

### ISSUE THREAD

**Issue by tschf** [OraOpenSource/OXAR#236]
Noticed this error during install

```
Commit complete.

   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER	NOCYCLE  NOT NULL ENABLE,
    	                                *
ERROR at line 2:
ORA-02000: missing ( keyword


      on aop_user_test for each row begin
         *
ERROR at line 3:
ORA-00942: table or view does not exist
```

https://github.com/OraOpenSource/OXAR/blob/d15a2e940d921fee388dfd06dfaccc96077bf4b1/addons/aop/aop_sample2_db_obj.sql

Guessing the identity column is causing it to fall overf

**Comment by dgielis** [comment]
Hi Trend,

I see AOP v2.4 is delivered with OXAR. Shall I upgrade to AOP 3.0?
Then immediately the above is fixed too.

Thanks,
Dimitri

**Comment by tschf** [comment]
Hi Dimitri... Ah yeah, cool. Can't see any issues with upgrading to the latest version :)

cc/ @martindsouza

**Comment by tschf** [comment]
Fixed it commit https://github.com/OraOpenSource/OXAR/commit/600a5bcdd90d88299a4aa55e99cdbd96fe5fa106
