### ISSUE TITLE
Error when installing OXAR with ORDS 3.0.11

### ISSUE THREAD

**Issue by GasparYYC** [OraOpenSource/OXAR#239]
Error when installing OXAR with ORDS 3.0.11:

`This version of ORDS is not yet supprted in OXAR
Please report this at http://github.com/OraOpenSource/oxar/issues
`

**Comment by tschf** [comment]
I created a branch with the changes. Haven't tested yet, so if you happen to be running again, let me know if all is good

**Comment by tschf** [comment]
Should be resolved in #240
