### ISSUE TITLE
Node.js version needs to be updated

### ISSUE THREAD

**Issue by fuzziebrain** [OraOpenSource/OXAR#242]
Either revert to 6.x LTS or move to the newer 8.x  release.

**Comment by tschf** [comment]
@fuzziebrain Resolved in your pull request #240?

**Comment by fuzziebrain** [comment]
Resolved

**Comment by joelmacklow** [comment]
Just tried a fresh install on CentOS 7.2 using this update and get a loop of this:
`gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/oracledb/.node-gyp/8.9.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/oracledb/.node-gyp"`

**Comment by fuzziebrain** [comment]
Issue tracked here:  #243
