### ISSUE TITLE
vagrant install - stuck in loop?

### ISSUE THREAD

**Issue by jfbleach** [OraOpenSource/OXAR#243]
I'm trying to install OXAR using the vagrant method and everything goes well until it starts getting this message over and over and over -
 gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/oracledb/.node-gyp"
==> default: gyp WARN EACCES user "root" does not have permission to access the dev dir "/usr/lib/node_modules/oracledb/.node-gyp/8.9.0"
==> default: gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/oracledb/.node-gyp"

I found that the last thing in the install log is:
> node-gyp rebuild

**Comment by joelmacklow** [comment]
I've found the same thing with native as well. If you Ctrl-C when the error loop is rolling the install will continue, but I'm not sure if it is complete or not

**Comment by fuzziebrain** [comment]
The fix is in branch fuzziebrain/issue-243 if you want to give it a try.

**Comment by tschf** [comment]
I just merged the PR, so you can give master a try too :+1:

**Comment by joelmacklow** [comment]
Have just spun up a clean CentOS 7.4 VM and installed from clean and confirm the error is resolved. Install progresses cleanly through.

**Comment by fuzziebrain** [comment]
Thanks for the feedback and testing.
