### ISSUE TITLE
Blank screen after installation on Digital Ocean

### ISSUE THREAD

**Issue by hairpin666** [OraOpenSource/OXAR#246]
Hi,

I tried to publish OXAR on a Digital Ocean Server.

The script run succesfull but when I try to call the Apex URL I only get a blank screen without any content.

Is there a step I missed.

Thanks

**Comment by fuzziebrain** [comment]
Was this recent and what's the distro and release version of the base image you used?

**Comment by hairpin666** [comment]
Yes, the it was last week. Used the latest distro available here. I just recreated the droplet still the same thing. I'm using a 1GB RAM droplet.

**Comment by fuzziebrain** [comment]
If it's a CentOS 7.4, then have a look at #241 and see if it's related.

**Comment by hairpin666** [comment]
Now, I get a 404 ords error saying the request couldn't be allocated to a  database....

**Comment by fuzziebrain** [comment]
You might have to perform the ORDS installation again. The alternative is to recreate the image and then do the steps in #241 before running the build script.

**Comment by hairpin666** [comment]
Thanks I'll try.
Can't I just disable SELinux ?

**Comment by fuzziebrain** [comment]
You could. Before 7.4, I believe DO didn't have SELinux enforcing by default.

**Comment by fuzziebrain** [comment]
Issue is addressed in #241 .
