### ISSUE TITLE
Documentation Enhacement - Upgrade OXAR to latest APEX patchset

### ISSUE THREAD

**Issue by GasparYYC** [OraOpenSource/OXAR#250]
I propose  a new document/section on the github page of OXAR that has specific information about applying a patcheset to Oracle APEX.
Doesn't have to be complex, it's very simply actually:

1. Unzip the patchset in a directory owned by oracle:dba 
2. Shutdown node4ords and tomcat:
```
# pm2 stop node4ords
# systemctl stop tomcat@oxar
```
3. Backup your database
 You can use your preferred way to backup or clone your server for better protection.
4. Change directory to the patchset_folder/patch
5. Connect SYS as SYSDBA to the database and run apxpatch.sql
via: 
```$ sqlplus /nolog
SQL> CONNECT SYS as SYSDBA
Enter password: SYS_password 
SQL> @apxpatch.sql 
```
6. As **root** copy new images files to /ords/apex_images
```
# cd /ords/apex_images
# cp -r /u01/app/oracle/PatchetFolder_Name/patch/images .
```
7. Reboot your server 

I just upgraded my OXAR installation from 5.1.0 to 5.1.4 and everything worked flawless.
The script took 5 mins. on my VM
The Patchset Documentation is a bit too complex and because of OXAR way of installing we can do a target specific document on how to apply it.

thanks for your consideration

**Comment by fuzziebrain** [comment]
Unless things have changed, Oracle patch sets are only available through My Oracle Support. That requires a support contract and I do not anticipate that many people who use OXAR have that access. I personally would avoid giving the impression that one could easily obtain and apply these patches. 

My two cents.
