### ISSUE TITLE
OXAR 18.1.1 not allowed...

### ISSUE THREAD

**Issue by GasparYYC** [OraOpenSource/OXAR#252]
Hi.
 Well today is APEX 18.1 day..
So we need to kick the tires **OXAR style...**

First things first.. ORDS 18.1 is a no-go

Thanks

**Comment by juliusgy** [comment]
You can install with a version supported by OXAR and then upgrade to the latest version.

**Comment by GasparYYC** [comment]
@juliusgy Yes and no... 
I meant that it needs to be inclusive for new installations.
OXAR installations have not been tested with upgrades.. 
Anecdotally upgrade of APEX works fine.
Upgrades to Tomcat - Unknown.
Upgrades to ORDS - Unknown.

**Comment by juliusgy** [comment]
That makes sense, I had an issues installing OXAR with ORDS 18.1 to the point where it wouldn't even work. Had to resort to the version allowed in the distribution and then do the upgrade afterward. Not ideal to be honest.

**Comment by fuzziebrain** [comment]
@GasparYYC Thanks for raising the issue. We'll need to make a change in one of the scripts for the install to work correctly. I will do that after Kscope18. A little busy right now.

**Comment by fuzziebrain** [comment]
OXAR should support both APEX 18.1 and ORDS 18.1.1 now. Note that if you are installing APEX 18.1, please disable AOP installation for now.
