### ISSUE TITLE
Press Enter to Continue?? - When Installing OXAR on CentOS 7.5 on Digital Ocean

### ISSUE THREAD

**Issue by GasparYYC** [OraOpenSource/OXAR#255]
This time I had to press Enter 3 times:
This is just weird, cause it was not the case before... Possibly a quirk with the latest CentOS Bash?

```...
Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
Oracle installed. Press enter to continue...

* Installing APEX *
```

```...

Disconnected from Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production
APEX installed. Press enter to continue...

* Installing node-oracledb *
```

```...
INFO: Modified: /etc/ords/defaults.xml, setting: apex.excel2collection.useSheetName = true
ORDS installed. Press enter to continue...
```

**Comment by tschf** [comment]
This was added in some time ago by Martin.
e.g. https://github.com/OraOpenSource/OXAR/blob/master/build.sh#L116-L118
and added from this issue https://github.com/OraOpenSource/OXAR/issues/166

Doing a quick inspection, it looks like it toggles that on when you start the script with the debug flag (-d|--debug).

**Comment by GasparYYC** [comment]
@tschf Oops I forgot I had edited and enabled the debug testing for item #254 and never put it back with the defaults of FALSE.

Sorry for the confusion, I think this item can be closed.
