### ISSUE TITLE
This version of ORDS is not yet supprted in OXAR (ORDS 18.2.0)

### ISSUE THREAD

**Issue by jsreyesn** [OraOpenSource/OXAR#256]
Error when installing OXAR with ORDS 18.2.0:

This version of ORDS is not yet supprted in OXAR
Please report this at http://github.com/OraOpenSource/oxar/issues

**Comment by GasparYYC** [comment]
Actually ORDS 18.3 has been released... 

Thanks

**Comment by fuzziebrain** [comment]
Thanks to @maxime-tremblay , we now have support for up to ORDS 18.3.
