### ISSUE TITLE
Add support for XE 18c

### ISSUE THREAD

**Issue by 4223** [OraOpenSource/OXAR#258]

**Comment by GasparYYC** [comment]
Yeah, we want 18c! No pressure 😜

**Comment by martindsouza** [comment]
OXAR is near EOL as we're looking at shifting everything towards docker. As such I don't think we'll be updating OXAR for XE 18c. We should have news about a docker XE 18c image early next week.

**Comment by 4223** [comment]
Docker image sounds great, thank you.
