### ISSUE TITLE
Where to put manifest.json and sw.js on OXAR

### ISSUE THREAD

**Issue by allipierre** [OraOpenSource/OXAR#261]
Hallo All,

 many thanks to all the people who made the OXAR work.

 I followed Vincent's great complete Guide  about PWA and could put manifest.json and sw.js in my local system under 
/webapps/ROOT in Tomcat. It worked great. Now I would like to do it in OXAR too. I would like to know where to put manifest.json and sw.js in OXAR.

Regards

Pierre

**Comment by fuzziebrain** [comment]
Hi @allipierre ,

Thank you for your question, but unfortunately, this is out of scope for OXAR. You might want to post the question [here](https://github.com/vincentmorneau/apex-pwa/issues) instead.

**Comment by allipierre** [comment]
Hi Adrian,

thanks you. You are right. I will post there. By the way the PWA Guide asks to put this files to the root of the APEX server. Where exactly can I find the Root of the APEX Server on the OXAR? 

Regards

Pierre
