### ISSUE TITLE
Add Uninstall script

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/OXAR#31]
For some servers with existing content on it, may want to uninstall everything that the build script does (since can't just rebuild machine from scratch).

Tough parts may be to remove content from existing configurations files.

**Comment by trent-** [comment]
At least for modifications to /etc/profile, the better practice as per comments in /etc/profile is to create a shell script in /etc/profile.d that then gets sourced:

>It's NOT a good idea to change this file unless you know what you
are doing. It's much better to create a custom.sh shell script in
/etc/profile.d/ to make custom changes to your environment, as this
will prevent the need for merging in future updates.

Maybe have a script for each module, that goes in /etc/profile.d

**Comment by martindsouza** [comment]
Given everything that OXAR does now and where it's going I don't think this is reasonable to do anymore.
