### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by martindsouza** [OraOpenSource/OXAR#33]
Waiting for let's Encrypt: https://letsencrypt.org/

Note: Part of this will be node4ords updates and some OXAR

- [x] Make this configurable in 
- [x] Enable https configuration: https://github.com/OraOpenSource/node4ords/issues/2
- [x] Confirguable location for cert files
- [x] How to create dummy web server . **Update:** From Gaspar: We may not need to run our own dummy web server. `certbot` may do it for us. Need to review API.
- [x] Option to reference custom certs
- [x] Option to create custom certs
- [x] Force SSL: http://stackoverflow.com/questions/10697660/force-ssl-with-expressjs-3 https://github.com/OraOpenSource/node4ords/issues/2
- [x] Enable firewall `firewall-cmd --zone=public --add-service=https --permanent`

Technical notes:

- Need to stop node4ords and run a "dummy" web server

`systemctl stop node4ords`

```js
var express = require('express');
var http = require('http');
var app = express();

// TODO some directory to store a blank index.html
app.use(express.static(config.static.directory));

http.createServer(app).listen(config.web.http.port);
```

From https://certbot.eff.org/#centosrhel7-other

```bash
# Install Certbot
yum install certbot

# generate cert
certbot certonly --webroot -w /var/www/public -d demo.oraopensource.com -m martin@oraopensource.com --agree-tos

# Certs are now /etc/letsencrypt/live/<domain>
```

**Comment by trent-** [comment]
https://letsencrypt.org/2015/06/16/lets-encrypt-launch-schedule.html

> **Let's Encrypt Launch Schedule**
* First certificate: Week of July 27, 2015
* General availability: Week of September 14, 2015

**Comment by tschf** [comment]
https://letsencrypt.org/2015/08/07/updated-lets-encrypt-launch-schedule.html

Schedule pushed back

> We’ve decided to push our launch schedule back a bit to give us time to further improve our systems. Our new schedule is:
* First certificate: Week of September 7, 2015
* General availability: Week of November 16, 2015

**Comment by 4223** [comment]
Is it still planned to implement LetsEncrypt in the OXAR-scripts?

**Comment by tschf** [comment]
Yes, that would be good. I haven't had time to try setting it up yet to see
what's involved. Whether that be a document describing the process or baked
in to the scripts, I'm not sure yet.

**Comment by martindsouza** [comment]
Script to generate SSL Certificate

```bash
openssl genrsa -out key_name.key 2048

openssl req -out CSR.csr -key key_name.key -new -sha256  -days 36 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"

https://www.digitalocean.com/community/tutorials/openssl-essentials-working-with-ssl-certificates-private-keys-and-csrs
openssl req \
       -newkey rsa:2048 -nodes -keyout domain.key \
       -out domain.csr \
       -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=www.example.com"

-- This should work.
openssl req \
      -newkey rsa:2048 -nodes -keyout domain.key \
      -x509 -days 365 -out domain.crt \
      -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost"

openssl genrsa -out domain-key.pem 1024
openssl req -new -key domain-key.pem -out certrequest.csr -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost"
openssl x509 -req -in certrequest.csr -signkey domain-key.pem -out domain-cert.pem
```

**Comment by martindsouza** [comment]
@4223 We now have SSL and Let's Encrypt done!
